Feature/sprint1
ClevertecFrontendLab/sprint1-alexkochnev1987 pull request #1
Opened 2023-01-28 15:51 UTC by alexkochnev1987

1. Task: https://docs.google.com/document/d/1Fx2uK9zP7Nk3fYa9WB_bB-x_p9fdHdnjJJW_ViC7bxk/edit

2023-01-28 15:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674921236/content-window.png)

2023-01-28 15:57 UTC, SergeyGlazun requested changes
на 320 проверти размер карточки, распространённая ошибка из за этого бот не может ее покликать

2023-01-28 16:00 UTC, SergeyGlazun commented
![Screenshot_1](https://user-images.githubusercontent.com/70904466/215276411-538321ab-521f-4755-bbcb-f46ee943faad.png)
также проверти жирность шрифта, отступы на соответствие с макетом

2023-01-28 17:20 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674926443/content-window.png)

2023-01-28 17:51 UTC, SergeyGlazun commented
![Screenshot_2](https://user-images.githubusercontent.com/70904466/215282737-bd0c8b0b-3556-4b3a-9673-1d53410ad0f6.png)
![Screenshot_1](https://user-images.githubusercontent.com/70904466/215282739-79ce7e29-6c63-41fb-8482-3f300232925a.png)
проверти размер карточки на 320 у многих была такая ошибка но потом размер приводили в норму и тест проходил, также проверти параметры текста в фирме и ваши

2023-01-28 17:52 UTC, SergeyGlazun requested changes
проверти параметры текста и размер карточки на 320

2023-01-28 18:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674930827/content-window.png)

2023-01-28 19:00 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215286054-1a231b96-9fe9-4e35-9f57-c1588df7846e.png)
а что поменялось?)

2023-01-28 21:07 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674940027/content-window.png)

2023-01-28 21:31 UTC, alexkochnev1987 commented
Вроде наложил pixelperfect на content-window320 и локально тесты проходят.
<img width="449" alt="image" src="https://user-images.githubusercontent.com/92919510/215292098-9e5e6f08-b038-4704-8a5e-6abfb52f4738.png">

2023-01-29 09:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674984406/content-window.png)

2023-01-29 10:25 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215319936-192f15d4-0b21-4dd5-b832-4acaad89eb22.png)
у вас не доходит до 320 а уже скол есть также и на 320 а его быть не должно для отладки жмите F12

2023-01-29 10:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674988485/content-window.png)

2023-01-29 10:46 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215320555-2b864af3-855c-4869-9381-640899eae796.png)
такая же проблем обнаружена на ширине больше 9 
![image](https://user-images.githubusercontent.com/70904466/215320660-7fc7146e-b64d-4b2e-b220-a2a9c39f8ee4.png)
00

больше 600 
![image](https://user-images.githubusercontent.com/70904466/215320766-3108312a-5d34-4628-8d05-d77277dd387e.png)
320 не решена  скролда вообше нигде не должно появляться ниже 300 
![image](https://user-images.githubusercontent.com/70904466/215320989-6c2259f4-c1b3-4840-9657-e22c3cc31e5f.png)

2023-01-29 10:52 UTC, SergeyGlazun commented
проверти где у вас фиксированные величины например у вас кнопка стоит with 320 так не правильно вы можете укать только минимальную величину например button> min-width: 100px при смене экрана вы также можете уменьшать размер шрифтов, в целом фиксированные размеры оч плохо для адаптива лучше тогда указывать минимальные или максимальные величины за которые они не могут опускаться или подниматься

2023-01-29 11:04 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/215321762-ad95c7ef-f6b1-4d29-9e05-1f6719d19c52.png)
также тут обратите внимание не соответствие макету, текс должен быть прижат левому краю блока, обратите внимание на задний фон а также что видны края блока прямоугольник и внутри карточка скругленные

2023-01-29 12:01 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 83.33333333333334%.
Общее количество тестов: 6.
Количество непройденных тестов: 1.
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1674993707/content-window.png)

2023-01-29 12:49 UTC, SergeyGlazun commented on src/index.css
> +  width: 1440px;
для контейнера лучше тоже указывать максимальную величину за какую он не сможет увеличиваться, для того что отсупы по кроям были лучше указывать margin: auto, для того что б выстроить контент в нужном порядке можно что нить вроде  display: flex;
    flex-direction: column;

2023-01-29 12:55 UTC, SergeyGlazun commented on src/index.css
> +    width: 768px;
у вас проблема с адаптивном потому что много длинны которая указанно константами типа witdth: 768 это значит что когда ваш экран станет 767px у вас появиться скролл, т.к  он в конкретной величине, лучше использовать flex  или грил и указывать как внутри блока должен располагаться контент максимум что указывать за какую величину они не должны становиться меньше или больше, константные размеры указываться в основном только для каких нить маленьких иконок чьи размеры 20-30px

2023-01-29 12:57 UTC, SergeyGlazun commented on src/pages/book/card-book-page/card-book-page.css
> +    padding: 1.25rem 0;
вот падинги лучше в константах делать pading: 10px;

2023-01-29 12:59 UTC, SergeyGlazun requested changes
проблема скрола не решена на разной ширине экрана 
![image](https://user-images.githubusercontent.com/70904466/215327724-82acc200-d558-4a67-8be9-59eb5a4f5cea.png)

2023-01-29 14:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675001311/content-window.png)

2023-01-29 16:00 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215338464-8e18d0c9-0046-416d-9a29-ecfd007b4248.png)
 320 победили) осталось победить остальные размеры экрана, в данный момент пользователю заблокирована часть контента, я бы советовал использовать https://tpverstak.ru/flex-cheatsheet/ 90% случаев вы можете там что то найти, для контейнера с карточками вы можете использовать display: flex; align-content: flex-start; тогда картоки сами будут перестраиваться при уменьшении ширины экрана

2023-01-29 20:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675023433/content-window.png)

2023-01-29 20:21 UTC, alexkochnev1987 commented
Буду благодарен за совет как лучше при ширине 596px.
<img width="992" alt="image" src="https://user-images.githubusercontent.com/92919510/215353681-e17c8918-9e9a-402b-a8f7-1967dd0b7b38.png">

И 951px
<img width="992" alt="image" src="https://user-images.githubusercontent.com/92919510/215353635-b38ee2aa-3a8e-4c89-af90-f17ecf68881f.png">

Когда идет перенос карточки на новый ряд. И как правильно поступать с пустыми местами.

2023-01-29 20:38 UTC, SergeyGlazun commented
изучитие внимательно https://tpverstak.ru/flex-cheatsheet/ ресурс там 90% рабочих ситуаций и размещение блоков можно решить или grid шпаргалка для прижатия контента по бокам justify-content: space-between; можете также для дочерних элиментов звдвть width: 30% значит 3 карточки на экра примерно с учетот margin 
![image](https://user-images.githubusercontent.com/70904466/215354520-b99e31d9-de3b-40e1-9b58-fcb0d7508d9c.png)
![image](https://user-images.githubusercontent.com/70904466/215354537-f3c65993-c2f7-4dfd-9d06-42d19f573b28.png)
вы можете комбинировать свойства

2023-01-29 20:39 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215354587-63977472-786c-479e-ab92-309ee391c9cd.png)
пользователю не доступен контент

2023-01-29 21:04 UTC, alexkochnev1987 commented
Не смог воссоздать недоступный контент на какой ширине это происходит?

2023-01-29 21:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675026278/content-window.png)

2023-01-29 21:17 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215355992-b2b22e41-8ada-4892-a9eb-f975cf768941.png)
почти достигли нужного результата но если доводить до конца это нужно делать по нормальному) этогонегативного пространста не должно быть, я же писал вам про это свойство) подрегултирйти только размер блока что б более красивее было 
![image](https://user-images.githubusercontent.com/70904466/215356128-904c0f19-998e-4548-ad8b-b97d687b9875.png)

2023-01-30 17:42 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675100536/content-window.png)

2023-01-30 17:53 UTC, SergeyGlazun approved these changes

2023-01-30 17:54 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/215555401-47885840-77db-4486-a836-d4ba898f4299.png)
обратите внимание гдето в arr.map забыли поставить key

2023-01-30 18:00 UTC, SergeyGlazun commented
вам апрув, можете мержить , но не забывайте расставлять ключи когда выводите через массив)

2023-01-30 18:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/alexkochnev1987/1675103221/content-window.png)

2023-01-30 18:34 UTC, merged